services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - ./config/env/.development.env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - struckly_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
  mailer:
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports:
      - 127.0.0.1:8025:8025
      - 127.0.0.1:1025:1025
volumes:
  struckly_data:
